### ISSUE TITLE
What is the real purpose of this plug-in ? 

### ISSUE THREAD

**Issue by bau720123** [simplec-dev/AndroidHomeIntent#1]
What is the real purpose of this plug-in ? 
in this page
https://build.phonegap.com/plugins/1085
it told as "This plugin adds home intents to android manifest so that your app can act as a launcher."
so...if can act as a launcher，is there any Advantages or ?

**Comment by kentmw** [comment]
+1 some explanation of the usefulness would be appreciated.

**Comment by simplec-dev** [comment]
Feel free to not use it if you don’t know what a home intent is.

**Comment by kentmw** [comment]
Just trying to understand the difference between what this project is offering and something like this project: https://github.com/ZhichengChen/cordova-plugin-android-home
which actually invokes the home intent. But if you don't want others using this project, that's fine too

**Comment by simplec-dev** [comment]
I don’t mean this snarky:  If they had private plugins when this was created, it would be private.  It was created to satisfy a specific goal for a company.

With regards to that other plugin, it is completely different.  A Home Intent (something worth googling) is an application that serves as the Launcher  for your Android device.  That other plugin is like pressing the home button.

**Comment by kentmw** [comment]
Thanks!
